#!/usr/bin/env bash
# Run ONCE on the server, before the first `docker compose up`.
# Generates real production secrets and writes:
#   - .env.production (repo root) -- consumed by the server/migrate containers
#   - deploy/init-roles.sql -- consumed by Postgres on first container startup
#
# Safe to re-run: if .env.production already exists, it is left untouched
# rather than silently regenerating passwords a running database already
# has baked in.

set -euo pipefail
cd "$(dirname "$0")/.."

if [ -f .env.production ]; then
  echo ".env.production already exists -- not overwriting. Delete it manually first if you really want to regenerate secrets."
  exit 0
fi

JIBUKS_APP_PASSWORD=$(openssl rand -base64 32 | tr -d '=+/')
JIBUKS_AUTH_RESOLVER_PASSWORD=$(openssl rand -base64 32 | tr -d '=+/')
JIBUKS_MIGRATOR_PASSWORD=$(openssl rand -base64 32 | tr -d '=+/')
POSTGRES_SUPERUSER_PASSWORD=$(openssl rand -base64 32 | tr -d '=+/')

sed \
  -e "s|__JIBUKS_APP_PASSWORD__|${JIBUKS_APP_PASSWORD}|g" \
  -e "s|__JIBUKS_AUTH_RESOLVER_PASSWORD__|${JIBUKS_AUTH_RESOLVER_PASSWORD}|g" \
  -e "s|__JIBUKS_MIGRATOR_PASSWORD__|${JIBUKS_MIGRATOR_PASSWORD}|g" \
  deploy/init-roles.sql.template > deploy/init-roles.sql

cat > .env.production << ENVEOF
# Generated by deploy/bootstrap-secrets.sh -- DO NOT COMMIT.
POSTGRES_SUPERUSER_PASSWORD=${POSTGRES_SUPERUSER_PASSWORD}

DATABASE_URL=postgres://jibuks_app:${JIBUKS_APP_PASSWORD}@postgres:5432/jibuks_prod
AUTH_RESOLVER_DATABASE_URL=postgres://jibuks_auth_resolver:${JIBUKS_AUTH_RESOLVER_PASSWORD}@postgres:5432/jibuks_prod
MIGRATION_DATABASE_URL=postgres://jibuks_migrator:${JIBUKS_MIGRATOR_PASSWORD}@postgres:5432/jibuks_prod

# Fill these in manually before starting the app -- see the Auth0
# production application setup (separate from the dev/test applications).
AUTH0_DOMAIN=
AUTH0_AUDIENCE=

PORT=3000
NODE_ENV=production
ENVEOF

echo "Generated .env.production and deploy/init-roles.sql."
echo "Now edit .env.production and fill in AUTH0_DOMAIN and AUTH0_AUDIENCE before starting the containers."